### ISSUE TITLE
Redis Option

### ISSUE THREAD

**Issue by Pauldic** [danidee10/django-notifs#16]
This is more or less a feature request, we already use Redis and am thinking we will be better off using redis than RabitQM. 

Can you advise on how we can achieve this?

**Comment by danidee10** [comment]
Hi, @Pauldic do you mean Redis for the WebSocket channel? or for Celery?

**Comment by danidee10** [comment]
closing this issue because:

There are some new changes that should address this problem:
- Support for multiple delivery backends (Celery, [rq](https://python-rq.org/), and [django-channels workers](https://channels.readthedocs.io/en/stable/topics/worker.html)!
- Automatic retries (for some backends) and a lot of internal improvements.

Now, you don't have to use Celery and RabbitMQ, you can switch to the rq or django-channels delivery backend (with Redis)

please check out the latest [docs](https://django-notifs.readthedocs.io/en/latest/) and don't hesitate to ask questions/raise issues.
